sync with maxine 5980 complete

diff --git a/com.oracle.max.ve.shell/ext2setup b/com.oracle.max.ve.shell/ext2setup
--- a/com.oracle.max.ve.shell/ext2setup
+++ b/com.oracle.max.ve.shell/ext2setup
@@ -21,26 +21,52 @@
 # or visit www.oracle.com if you need additional information or have any
 # questions.
 #
-# Script to setup Maxine VE based on properties file values.
-# Should be run from VENative directory
+# Setup for other ext2 scripts
 #
 
-
+# Resolve location of this script
     me="${BASH_SOURCE[0]}"
     while [ -h "$me" ]; do
         me=`readlink -e "$me"`
     done
 
 me_dir=`dirname $me`
-propfile=$1
-if [ ! -e $propfile ];
-then
-    echo "Properties does not exist/is inaccessible"
-    exit 1
+export ve_dir=`cd $me_dir/..; pwd`
+
+
+if [ -n "${DISK}" ] ; then
+  dfile=$DISK
 fi
-wsroot=`dirname $PWD`
-dfile="maxve-disk1.img"
-cp=$wsroot/VEMain/bin:$wsroot/VEBase/bin:$wsroot/JNodeFS/bin
-mc=com.sun.max.ve.tools.ScratchPadGenerator
-h="-Dmax.ve.logging.handler=com.sun.max.ve.logging.SystemOutHandler -Dmax.ve.logging.level=WARNING"
-java -classpath $cp $h $mc $propfile
+mc=com.sun.max.ve.tools.ext2.Ext2FileTool
+h="-Dmax.ve.logging.handler=com.sun.max.ve.logging.SystemOutLogHandler -Dmax.ve.logging.level=WARNING"
+
+while [ "$1" != "" ];
+do
+  case $1 in
+    -disk )
+      shift
+      dfile=$1
+      ;;
+    -wsroot )
+      shift
+      ve_dir=$1
+      ;;
+    * )
+      break
+      ;;
+  esac
+  shift
+done
+
+if [ -z "$dfile" ]; then
+  echo "no disk specified, use -disk or set DISK environment variable"
+  exit 1
+fi
+
+cp=$ve_dir/com.oracle.max.ve/bin:$ve_dir/com.oracle.max.ve.base/bin:$ve_dir/com.oracle.max.ve.tools/bin:$ve_dir/com.oracle.max.ve.jnodefs/bin
+
+if [ ! -d "$ve_dir/com.oracle.max.ve.tools/bin" ] ;
+then
+  echo "cannot find classes for Ext2FileTool, set -wsroot to directory containing MaxVE projects"
+  exit 1;
+fi
diff --git a/com.oracle.max.ve.shell/maxve b/com.oracle.max.ve.shell/maxve
--- a/com.oracle.max.ve.shell/maxve
+++ b/com.oracle.max.ve.shell/maxve
@@ -24,10 +24,27 @@
 # A script that extends the Maxine "max" script to allow Maxine VE to be built
 # Author: Mick Jordan
 
-pushd .. >/dev/null
-export extra_projects_dirs=`pwd`
+# Try to find the base directory of the VE code base by using the path of this script
+# Resolve location of this script
+me="${BASH_SOURCE[0]}"
+while [ -h "$me" ]; do
+    me=`readlink -e "$me"`
+done
+pushd . >/dev/null
+cd `dirname "${me}"`
+cd ..
+ve_dir=`pwd`
 popd >/dev/null
 
+# Sanity check: is ${ve_dir}/com.oracle.max.ve.shell/maxve an executable
+if [ ! -x "${ve_dir}/com.oracle.max.ve.shell/maxve" ]; then
+    echo "Can't find Maxine VE code base at '${ve_dir}': '${ve_dir}/com.oracle.max.ve.shell/maxve' does not exist or is not an executable"
+    exit 1
+fi
+
+if [ -z "${extra_projects_dirs}" ]; then
+    export extra_projects_dirs=$ve_dir
+fi
 
 image_override=1
 vm_override=1
@@ -37,7 +54,7 @@ imageargs=""
 
 function run_image_override() {
   echo "build Maxine Virtual Edition image"
-  pushd ../../guk  >/dev/null
+  pushd $ve_dir/../guk  >/dev/null
   gmake
   popd  >/dev/null
   echo run ${jvm_exe} -cp $(jmax classpath) com.sun.max.vm.hosted.VEBootImageGenerator -trace=1 $prefix_classpath $specfile $imageargs $@
@@ -74,4 +91,8 @@ while [ "${1:0:1}" = "-" ]; do
     esac
     shift
 done
-. ../../maxine/com.oracle.max.shell/max $@
+
+pushd $ve_dir  >/dev/null
+. ../maxine/com.oracle.max.shell/max $@
+popd  >/dev/null
+
